import {
  Guard,
  Site,
  Incident,
  PatrolTour,
  Checkpoint,
  ShiftSchedule,
  AttendanceRecord,
  Invoice,
  BroadcastMessage,
  SystemNotification,
  Tenant,
  UserAccount,
} from './types';

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'usr-superadmin-1',
    name: 'Dr. Sipho Mokoena (Group SOC Director)',
    email: 'superadmin@aegisops.co.za',
    phone: '+27 (0) 11 884 9001',
    role: 'SUPERADMIN',
    status: 'ACTIVE',
    avatar: '👑',
    createdAt: '2026-01-01',
    lastLogin: 'Just now',
    assignedSitesCount: 28,
  },
  {
    id: 'usr-admin-apex',
    name: 'Cmdr. Thabo Ndlovu (Chief of Security)',
    email: 'tndlovu@aegis-sovereign.co.za',
    phone: '+27 (0) 11 884 9012',
    role: 'TENANT_ADMIN',
    tenantId: 'tenant-apex',
    tenantName: 'Aegis Southern Africa & Critical Infrastructure',
    status: 'ACTIVE',
    avatar: '🛡️',
    createdAt: '2026-01-15',
    lastLogin: '5 mins ago',
    assignedSitesCount: 12,
  },
  {
    id: 'usr-admin-cyber',
    name: 'Dr. Pieter van Zyl',
    email: 'pvanzyl@cybervault.co.za',
    phone: '+27 (0) 21 550 8911',
    role: 'TENANT_ADMIN',
    tenantId: 'tenant-cybervault',
    tenantName: 'Kalahari & CyberVault Hyperscale Data Centers',
    status: 'ACTIVE',
    avatar: '⚡',
    createdAt: '2026-02-01',
    lastLogin: '1 hour ago',
    assignedSitesCount: 8,
  },
  {
    id: 'usr-admin-freight',
    name: 'Kagiso Khumalo',
    email: 'kkhumalo@tl-freight.co.za',
    phone: '+27 (0) 31 368 4022',
    role: 'TENANT_ADMIN',
    tenantId: 'tenant-metropolis',
    tenantName: 'Trans-Limpopo Freight & Maritime Corridor',
    status: 'ACTIVE',
    avatar: '🚢',
    createdAt: '2026-02-10',
    lastLogin: '3 hours ago',
    assignedSitesCount: 10,
  },
  {
    id: 'usr-admin-heritage',
    name: 'Johan van der Merwe',
    email: 'johan@cape-estates.co.za',
    phone: '+27 (0) 21 888 7700',
    role: 'TENANT_ADMIN',
    tenantId: 'tenant-oasis',
    tenantName: 'Cape Sovereign Estates & Winelands Security',
    status: 'ACTIVE',
    avatar: '🏰',
    createdAt: '2026-03-01',
    lastLogin: 'Yesterday',
    assignedSitesCount: 6,
  },
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-apex',
    name: 'Aegis Southern Africa & Critical Infrastructure',
    code: 'AEGIS-ZA',
    industry: 'Financial Citadels, Mining Vaults & National Infrastructure',
    plan: 'Critical Infrastructure SLA',
    sitesCount: 12,
    guardsCount: 56,
    contactEmail: 'soc-jhb@aegisops.co.za',
    contactPhone: '+27 (0) 11 884 9012',
    monthlySpend: 285000,
    logo: '🛡️',
    color: '#171717',
    status: 'ACTIVE',
    createdAt: '2026-01-10',
    primaryAdminId: 'usr-admin-apex',
    primaryAdminName: 'Cmdr. Thabo Ndlovu',
    primaryAdminEmail: 'tndlovu@aegis-sovereign.co.za',
  },
  {
    id: 'tenant-cybervault',
    name: 'Kalahari & CyberVault Hyperscale Data Centers',
    code: 'CYBER-SA',
    industry: 'Subsea Cable Landings, Cloud Infrastructure & Fintech',
    plan: 'Enterprise Guard Suite',
    sitesCount: 8,
    guardsCount: 34,
    contactEmail: 'security@cybervault.co.za',
    contactPhone: '+27 (0) 21 550 8911',
    monthlySpend: 195000,
    logo: '⚡',
    color: '#404040',
    status: 'ACTIVE',
    createdAt: '2026-02-01',
    primaryAdminId: 'usr-admin-cyber',
    primaryAdminName: 'Dr. Pieter van Zyl',
    primaryAdminEmail: 'pvanzyl@cybervault.co.za',
  },
  {
    id: 'tenant-metropolis',
    name: 'Trans-Limpopo Freight & Maritime Corridor',
    code: 'TL-FREIGHT',
    industry: 'SADC Supply Chain, Durban Port & Rail Corridors',
    plan: 'Enterprise Guard Suite',
    sitesCount: 10,
    guardsCount: 42,
    contactEmail: 'operations@tl-freight.co.za',
    contactPhone: '+27 (0) 31 368 4022',
    monthlySpend: 245000,
    logo: '🚢',
    color: '#737373',
    status: 'ACTIVE',
    createdAt: '2026-02-10',
    primaryAdminId: 'usr-admin-freight',
    primaryAdminName: 'Kagiso Khumalo',
    primaryAdminEmail: 'kkhumalo@tl-freight.co.za',
  },
  {
    id: 'tenant-oasis',
    name: 'Cape Sovereign Estates & Winelands Security',
    code: 'CAPE-ESTATES',
    industry: 'Gated Wineland Reserves, Diplomatic & Luxury Enclaves',
    plan: 'Standard Security',
    sitesCount: 6,
    guardsCount: 22,
    contactEmail: 'control@cape-estates.co.za',
    contactPhone: '+27 (0) 21 888 7700',
    monthlySpend: 165000,
    logo: '🏰',
    color: '#525252',
    status: 'ACTIVE',
    createdAt: '2026-03-01',
    primaryAdminId: 'usr-admin-heritage',
    primaryAdminName: 'Johan van der Merwe',
    primaryAdminEmail: 'johan@cape-estates.co.za',
  },
];

export const INITIAL_SITES: Site[] = [
  // 1. Gauteng -> City of Johannesburg -> Sandton Financial District
  {
    id: 'site-sandton-citadel',
    tenantId: 'tenant-apex',
    name: 'Sandton Financial Citadel & Corporate Vaults',
    address: '135 Rivonia Road, Sandton, 2196',
    city: 'Johannesburg',
    state: 'Gauteng',
    country: 'South Africa',
    region: 'Gauteng Central',
    countyOrAuthority: 'City of Johannesburg',
    authorityType: 'Metropolitan Municipality',
    district: 'Sandton Central CBD',
    townOrCity: 'Johannesburg',
    locationCategory: 'City',
    postcode: '2196',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 0,
    networkLatencyMs: 2,
    localEmergencyAgency: 'SAPS Sandton (CAS 10111) / Netcare 911 Flying Squad',
    type: 'Financial Tower',
    activeGuardsCount: 6,
    totalCheckpoints: 6,
    mapCenter: { lat: -26.1076, lng: 28.0567 },
    geoMapPos: { x: 62, y: 38 },
    weather: {
      condition: 'Sunny Highveld',
      tempC: 24,
      tempF: 75,
      icon: '☀️',
    },
    emergencyContact: {
      name: 'Cmdr. Thabo Ndlovu',
      role: 'Chief Security Officer (PSIRA Grade A)',
      phone: '+27 (0) 11 884 9012',
    },
    zones: [
      {
        id: 'zone-san-1',
        siteId: 'site-sandton-citadel',
        name: 'Sovereign Bullion & SWIFT Vault Core',
        points: [{ x: 15, y: 15 }, { x: 50, y: 15 }, { x: 50, y: 45 }, { x: 15, y: 45 }],
        color: '#525252',
        accessLevel: 'VIP Vault',
        description: 'Class 4 EMP-shielded bullion vault with dual biometric retina airlocks.',
      },
      {
        id: 'zone-san-2',
        siteId: 'site-sandton-citadel',
        name: 'Tier-4 Subterranean Power & Solar Hybrid Grid',
        points: [{ x: 55, y: 15 }, { x: 90, y: 15 }, { x: 90, y: 45 }, { x: 55, y: 45 }],
        color: '#737373',
        accessLevel: 'High Security',
        description: '3.5MW dual diesel generators and 12MWh BESS solar backup storage.',
      },
      {
        id: 'zone-san-3',
        siteId: 'site-sandton-citadel',
        name: 'North Atrium & Executive Helipad Gate',
        points: [{ x: 15, y: 50 }, { x: 90, y: 50 }, { x: 90, y: 85 }, { x: 15, y: 85 }],
        color: '#64748B',
        accessLevel: 'Restricted',
        description: 'ANPR optical license scanner and armed response vehicle staging dock.',
      },
    ],
  },

  // 2. Gauteng -> Midrand Logistics & Industrial Hub
  {
    id: 'site-midrand-logistics',
    tenantId: 'tenant-apex',
    name: 'Midrand High-Tech Logistics & Bonded Freight Hub',
    address: 'Waterfall Commercial District, K101 Corridor, Midrand, 1685',
    city: 'Midrand',
    state: 'Gauteng',
    country: 'South Africa',
    region: 'Gauteng North',
    countyOrAuthority: 'City of Johannesburg',
    authorityType: 'Metropolitan Municipality',
    district: 'Waterfall City',
    townOrCity: 'Midrand',
    locationCategory: 'Industrial Zone',
    postcode: '1685',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 22,
    networkLatencyMs: 4,
    localEmergencyAgency: 'SAPS Midrand / Tactical Armed Response Unit 4',
    type: 'Logistics Hub',
    activeGuardsCount: 5,
    totalCheckpoints: 5,
    mapCenter: { lat: -25.9984, lng: 28.1263 },
    geoMapPos: { x: 63, y: 36 },
    weather: {
      condition: 'Clear Sky',
      tempC: 25,
      tempF: 77,
      icon: '☀️',
    },
    emergencyContact: {
      name: 'Insp. Willem de Klerk',
      role: 'Logistics Security Warden (PSIRA Grade A)',
      phone: '+27 (0) 11 315 4400',
    },
    zones: [
      {
        id: 'zone-mid-1',
        siteId: 'site-midrand-logistics',
        name: 'Pharmaceutical & High-Value Cold-Chain Vault',
        points: [{ x: 15, y: 15 }, { x: 50, y: 15 }, { x: 50, y: 55 }, { x: 15, y: 55 }],
        color: '#525252',
        accessLevel: 'High Security',
        description: 'Temperature-monitored bonded vault with QR scan security seal audits.',
      },
      {
        id: 'zone-mid-2',
        siteId: 'site-midrand-logistics',
        name: 'Heavy Haulage Intermodal Dock Bay 1-12',
        points: [{ x: 55, y: 15 }, { x: 90, y: 15 }, { x: 90, y: 85 }, { x: 55, y: 85 }],
        color: '#737373',
        accessLevel: 'Restricted',
        description: 'Weighbridge ANPR cameras, container seal verification and armed escort bays.',
      },
    ],
  },

  // 3. Western Cape -> City of Cape Town -> Century City Cyber Park
  {
    id: 'site-century-city-cyber',
    tenantId: 'tenant-cybervault',
    name: 'Century City Cyber Park & Subsea Cable Landing',
    address: 'Century Boulevard, Century City, Cape Town, 7441',
    city: 'Cape Town',
    state: 'Western Cape',
    country: 'South Africa',
    region: 'Western Cape Coast',
    countyOrAuthority: 'City of Cape Town',
    authorityType: 'Metropolitan Municipality',
    district: 'Century City Technology Zone',
    townOrCity: 'Cape Town',
    locationCategory: 'City',
    postcode: '7441',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 1390,
    networkLatencyMs: 14,
    localEmergencyAgency: 'SAPS Milnerton / ER24 Western Cape Metro Dispatch',
    type: 'Data Center',
    activeGuardsCount: 5,
    totalCheckpoints: 6,
    mapCenter: { lat: -33.8927, lng: 18.5113 },
    geoMapPos: { x: 26, y: 86 },
    weather: {
      condition: 'Coastal Breeze',
      tempC: 21,
      tempF: 70,
      icon: '🌤️',
    },
    emergencyContact: {
      name: 'Dr. Pieter van Zyl',
      role: 'Cyber Infrastructure Director',
      phone: '+27 (0) 21 550 8911',
    },
    zones: [
      {
        id: 'zone-cpt-1',
        siteId: 'site-century-city-cyber',
        name: 'Subsea Fiber Demarcation & Carrier Vault',
        points: [{ x: 10, y: 10 }, { x: 45, y: 10 }, { x: 45, y: 50 }, { x: 10, y: 50 }],
        color: '#A3A3A3',
        accessLevel: 'VIP Vault',
        description: 'Direct landing point for 2Africa & Equiano ultra-bandwidth cables.',
      },
      {
        id: 'zone-cpt-2',
        siteId: 'site-century-city-cyber',
        name: 'Hyperscale Server Hall Alpha & Beta',
        points: [{ x: 50, y: 10 }, { x: 90, y: 10 }, { x: 90, y: 50 }, { x: 50, y: 50 }],
        color: '#525252',
        accessLevel: 'High Security',
        description: 'Biometric mantle-trap access with nitrogen fire suppression.',
      },
    ],
  },

  // 4. KwaZulu-Natal -> eThekwini -> Durban Port & Bayhead
  {
    id: 'site-durban-port-terminal',
    tenantId: 'tenant-metropolis',
    name: 'Durban Port & Bayhead Container Logistics Terminal',
    address: 'Bayhead Road, Durban Container Terminal, Durban, 4052',
    city: 'Durban',
    state: 'KwaZulu-Natal',
    country: 'South Africa',
    region: 'KZN Coastal Port',
    countyOrAuthority: 'eThekwini Metropolitan Municipality',
    authorityType: 'Metropolitan Municipality',
    district: 'Durban Port Logistics Zone',
    townOrCity: 'Durban',
    locationCategory: 'Port Terminal',
    postcode: '4052',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 570,
    networkLatencyMs: 8,
    localEmergencyAgency: 'SAPS Port Security & Maritime Police / Transnet Security',
    type: 'Port Facility',
    activeGuardsCount: 6,
    totalCheckpoints: 6,
    mapCenter: { lat: -29.8789, lng: 31.0218 },
    geoMapPos: { x: 82, y: 59 },
    weather: {
      condition: 'Subtropical Humid',
      tempC: 27,
      tempF: 81,
      icon: '⛅',
    },
    emergencyContact: {
      name: 'Capt. Zanele Sithole',
      role: 'Port Facility Security Officer (ISPS Certified)',
      phone: '+27 (0) 31 368 4022',
    },
    zones: [
      {
        id: 'zone-dbn-1',
        siteId: 'site-durban-port-terminal',
        name: 'Pier 2 Deepwater Gantry & Customs Bay',
        points: [{ x: 10, y: 10 }, { x: 50, y: 10 }, { x: 50, y: 60 }, { x: 10, y: 60 }],
        color: '#525252',
        accessLevel: 'High Security',
        description: 'ISPS Code compliant international maritime perimeter and customs seals.',
      },
      {
        id: 'zone-dbn-2',
        siteId: 'site-durban-port-terminal',
        name: 'Rail Shunting Yard & Dangerous Goods Compound',
        points: [{ x: 55, y: 10 }, { x: 90, y: 10 }, { x: 90, y: 85 }, { x: 55, y: 85 }],
        color: '#737373',
        accessLevel: 'Restricted',
        description: 'Transnet freight rail link connecting Durban Port to City Deep, Johannesburg.',
      },
    ],
  },

  // 5. Western Cape -> V&A Waterfront Maritime & Marina Precinct
  {
    id: 'site-v-and-a-waterfront',
    tenantId: 'tenant-oasis',
    name: 'V&A Waterfront Maritime & Luxury Marina Precinct',
    address: '19 Dock Road, Victoria & Alfred Waterfront, Cape Town, 8001',
    city: 'Cape Town',
    state: 'Western Cape',
    country: 'South Africa',
    region: 'Western Cape Coast',
    countyOrAuthority: 'City of Cape Town',
    authorityType: 'Metropolitan Municipality',
    district: 'Table Bay Foreshore',
    townOrCity: 'Cape Town',
    locationCategory: 'City',
    postcode: '8001',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 1395,
    networkLatencyMs: 14,
    localEmergencyAgency: 'SAPS Table Bay Harbour / Metro Police Water Wing',
    type: 'Corporate HQ',
    activeGuardsCount: 4,
    totalCheckpoints: 5,
    mapCenter: { lat: -33.9036, lng: 18.4206 },
    geoMapPos: { x: 25, y: 87 },
    weather: {
      condition: 'Clear & Oceanic',
      tempC: 22,
      tempF: 72,
      icon: '☀️',
    },
    emergencyContact: {
      name: 'Superintendent Pieter Botha',
      role: 'Waterfront Operations Commander',
      phone: '+27 (0) 21 408 7500',
    },
    zones: [
      {
        id: 'zone-vna-1',
        siteId: 'site-v-and-a-waterfront',
        name: 'Superyacht Basin & Private Helipad Zone',
        points: [{ x: 15, y: 15 }, { x: 85, y: 15 }, { x: 85, y: 70 }, { x: 15, y: 70 }],
        color: '#A3A3A3',
        accessLevel: 'High Security',
        description: 'Underwater sonar sensors and diplomatic yacht mooring.',
      },
    ],
  },

  // 6. Gauteng -> City of Tshwane (Pretoria) -> Innovation Hub
  {
    id: 'site-tshwane-innovation',
    tenantId: 'tenant-cybervault',
    name: 'Tshwane Innovation Hub & National Cyber Defense Campus',
    address: '1 Mark Shuttleworth Street, Persequor, Pretoria, 0020',
    city: 'Pretoria',
    state: 'Gauteng',
    country: 'South Africa',
    region: 'Gauteng North',
    countyOrAuthority: 'City of Tshwane',
    authorityType: 'Metropolitan Municipality',
    district: 'Hatfield Innovation Corridor',
    townOrCity: 'Pretoria',
    locationCategory: 'City',
    postcode: '0020',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 55,
    networkLatencyMs: 5,
    localEmergencyAgency: 'SAPS Brooklyn / State Security Agency (SSA) Cyber Taskforce',
    type: 'Research Park',
    activeGuardsCount: 4,
    totalCheckpoints: 5,
    mapCenter: { lat: -25.7511, lng: 28.2678 },
    geoMapPos: { x: 63, y: 34 },
    weather: {
      condition: 'Warm Jacaranda Air',
      tempC: 26,
      tempF: 79,
      icon: '☀️',
    },
    emergencyContact: {
      name: 'Col. Lungile Mthembu',
      role: 'Cyber-Physical Security Marshall',
      phone: '+27 (0) 12 844 0000',
    },
    zones: [
      {
        id: 'zone-tsh-1',
        siteId: 'site-tshwane-innovation',
        name: 'Cryptographic Hardware Test Cell',
        points: [{ x: 15, y: 15 }, { x: 85, y: 15 }, { x: 85, y: 70 }, { x: 15, y: 70 }],
        color: '#E11D48',
        accessLevel: 'High Security',
        description: 'Shielded TEMPEST lab for critical infrastructure cryptographic keys.',
      },
    ],
  },

  // 7. Gauteng -> Ekurhuleni -> OR Tambo International Cargo Security Hub
  {
    id: 'site-or-tambo-cargo',
    tenantId: 'tenant-metropolis',
    name: 'OR Tambo International Cargo & Bonded Customs Hub',
    address: 'Jones Road, Cargo Terminal 4, Kempton Park, 1627',
    city: 'Kempton Park',
    state: 'Gauteng',
    country: 'South Africa',
    region: 'Gauteng East',
    countyOrAuthority: 'City of Ekurhuleni',
    authorityType: 'Metropolitan Municipality',
    district: 'Aerotropolis Corridor',
    townOrCity: 'Kempton Park',
    locationCategory: 'Port Terminal',
    postcode: '1627',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 28,
    networkLatencyMs: 4,
    localEmergencyAgency: 'SAPS OR Tambo Airport Police / SARS Customs Canine Unit',
    type: 'Logistics Hub',
    activeGuardsCount: 5,
    totalCheckpoints: 5,
    mapCenter: { lat: -26.1367, lng: 28.2411 },
    geoMapPos: { x: 65, y: 39 },
    weather: {
      condition: 'Sunny Intervals',
      tempC: 23,
      tempF: 73,
      icon: '🌤️',
    },
    emergencyContact: {
      name: 'Insp. Tariro Moyo',
      role: 'Air Cargo Security Commander',
      phone: '+27 (0) 11 921 6262',
    },
    zones: [
      {
        id: 'zone-ort-1',
        siteId: 'site-or-tambo-cargo',
        name: 'Precious Metals & Banknote Air Transit Vault',
        points: [{ x: 10, y: 10 }, { x: 90, y: 10 }, { x: 90, y: 75 }, { x: 10, y: 75 }],
        color: '#525252',
        accessLevel: 'High Security',
        description: 'Armored tarmac airside staging for gold bullion and high-value diamonds.',
      },
    ],
  },

  // 8. Western Cape -> Cape Winelands -> Stellenbosch Sovereign Estate
  {
    id: 'site-stellenbosch-reserve',
    tenantId: 'tenant-oasis',
    name: 'Stellenbosch Agri-Tech & Heritage Sovereign Reserve',
    address: 'Helshoogte Pass, Banhoek Valley, Stellenbosch, 7600',
    city: 'Stellenbosch',
    state: 'Western Cape',
    country: 'South Africa',
    region: 'Cape Winelands',
    countyOrAuthority: 'Cape Winelands District Municipality',
    authorityType: 'District Municipality',
    district: 'Banhoek Valley',
    townOrCity: 'Stellenbosch',
    locationCategory: 'Town',
    postcode: '7600',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 1380,
    networkLatencyMs: 14,
    localEmergencyAgency: 'SAPS Stellenbosch / Winelands Tactical Reaction Team',
    type: 'Heritage Estate',
    activeGuardsCount: 4,
    totalCheckpoints: 5,
    mapCenter: { lat: -33.9214, lng: 18.9134 },
    geoMapPos: { x: 28, y: 88 },
    weather: {
      condition: 'Mountain Sunshine',
      tempC: 24,
      tempF: 75,
      icon: '🍇',
    },
    emergencyContact: {
      name: 'Johan van der Merwe',
      role: 'Estate Security Director',
      phone: '+27 (0) 21 888 7700',
    },
    zones: [
      {
        id: 'zone-ste-1',
        siteId: 'site-stellenbosch-reserve',
        name: 'Private Cellar Vault & Heritage Archives',
        points: [{ x: 15, y: 15 }, { x: 85, y: 15 }, { x: 85, y: 70 }, { x: 15, y: 70 }],
        color: '#737373',
        accessLevel: 'High Security',
        description: 'Thermal climate-controlled historic cellars and perimeter thermal fencing.',
      },
    ],
  },

  // 9. SADC Regional Hub -> Botswana -> Gaborone CBD
  {
    id: 'site-gaborone-diamond-hub',
    tenantId: 'tenant-apex',
    name: 'Gaborone Diamond & Sovereign Logistics Center',
    address: 'Plot 54351, Central Business District, Gaborone, Botswana',
    city: 'Gaborone',
    state: 'South-East District',
    country: 'Botswana',
    region: 'SADC Cross-Border Hub',
    countyOrAuthority: 'Gaborone City Council',
    authorityType: 'City',
    district: 'CBD Gaborone',
    townOrCity: 'Gaborone',
    locationCategory: 'City',
    postcode: 'BW-00267',
    timezone: 'Africa/Gaborone',
    timezoneOffset: 'CAT (UTC+2)',
    distanceKmFromHQ: 360,
    networkLatencyMs: 12,
    localEmergencyAgency: 'Botswana Police Service (BPS Central) / Special Support Group',
    type: 'Financial Tower',
    activeGuardsCount: 4,
    totalCheckpoints: 5,
    mapCenter: { lat: -24.6541, lng: 25.9087 },
    geoMapPos: { x: 50, y: 25 },
    weather: {
      condition: 'Warm Kalahari Sun',
      tempC: 28,
      tempF: 82,
      icon: '☀️',
    },
    emergencyContact: {
      name: 'Major Kgosi Khumalo',
      role: 'Diamond Vault Security Officer',
      phone: '+267 391 2000',
    },
    zones: [
      {
        id: 'zone-gab-1',
        siteId: 'site-gaborone-diamond-hub',
        name: 'Rough Diamond Sorting & Export Vault',
        points: [{ x: 15, y: 15 }, { x: 85, y: 15 }, { x: 85, y: 70 }, { x: 15, y: 70 }],
        color: '#525252',
        accessLevel: 'VIP Vault',
        description: 'High-security rough and polished diamond grading and export vault.',
      },
    ],
  },

  // 10. KwaZulu-Natal -> eThekwini -> Umhlanga Ridge Sovereign Security Zone
  {
    id: 'site-umhlanga-ridge',
    tenantId: 'tenant-apex',
    name: 'Umhlanga Ridge Sovereign Financial & Tech Park',
    address: 'Palm Boulevard, Umhlanga Rocks, Durban, 4319',
    city: 'Durban',
    state: 'KwaZulu-Natal',
    country: 'South Africa',
    region: 'KZN North Coast',
    countyOrAuthority: 'eThekwini Metropolitan Municipality',
    authorityType: 'Metropolitan Municipality',
    district: 'Umhlanga Ridge CBD',
    townOrCity: 'Durban',
    locationCategory: 'City',
    postcode: '4319',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 'SAST (UTC+2)',
    distanceKmFromHQ: 580,
    networkLatencyMs: 9,
    localEmergencyAgency: 'SAPS Durban North / Marshall Security Armed Reaction',
    type: 'Corporate HQ',
    activeGuardsCount: 4,
    totalCheckpoints: 5,
    mapCenter: { lat: -29.7275, lng: 31.0664 },
    geoMapPos: { x: 83, y: 57 },
    weather: {
      condition: 'Tropical Sunshine',
      tempC: 26,
      tempF: 79,
      icon: '☀️',
    },
    emergencyContact: {
      name: 'Insp. Naledi Dlamini',
      role: 'Ridge Security Commander',
      phone: '+27 (0) 31 566 8000',
    },
    zones: [
      {
        id: 'zone-umh-1',
        siteId: 'site-umhlanga-ridge',
        name: 'Oceanview Financial Server Core',
        points: [{ x: 10, y: 10 }, { x: 90, y: 10 }, { x: 90, y: 80 }, { x: 10, y: 80 }],
        color: '#525252',
        accessLevel: 'High Security',
        description: 'Redundant fiber hub linking to Durban subsea cable routes.',
      },
    ],
  },
];

export const INITIAL_CHECKPOINTS: Checkpoint[] = [
  // Sandton Checkpoints
  {
    id: 'cp-san-01',
    name: 'CP-01: Sovereign Bullion Vault Dual-Airlock Tag',
    siteId: 'site-sandton-citadel',
    location: { x: 25, y: 25 },
    type: 'QR Code Scan',
    requiredAction: 'Scan physical QR tag; verify biometric iris lock seal & pressure',
    minDwellSeconds: 45,
    targetWindowMinutes: 20,
    isHighSecurity: true,
    qrCodeValue: 'QR-SAN-VAULT-01',
  },
  {
    id: 'cp-san-02',
    name: 'CP-02: Hybrid BESS Solar & Diesel Power Core',
    siteId: 'site-sandton-citadel',
    location: { x: 70, y: 25 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; verify generator fuel reserve & inverter output',
    minDwellSeconds: 60,
    targetWindowMinutes: 30,
    isHighSecurity: true,
    qrCodeValue: 'QR-SAN-POWER-02',
  },
  {
    id: 'cp-san-03',
    name: 'CP-03: Perimeter North Gate ANPR & Boom Lock',
    siteId: 'site-sandton-citadel',
    location: { x: 50, y: 65 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; verify heavy hydraulic tyre killers & barrier lock',
    minDwellSeconds: 30,
    targetWindowMinutes: 15,
    isHighSecurity: false,
    qrCodeValue: 'QR-SAN-GATE-03',
  },

  // Midrand Checkpoints
  {
    id: 'cp-mid-01',
    name: 'CP-01: Bonded Cold-Chain Pharmaceutical Vault',
    siteId: 'site-midrand-logistics',
    location: { x: 30, y: 30 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; verify -20C digital temp logger & electronic seals',
    minDwellSeconds: 60,
    targetWindowMinutes: 20,
    isHighSecurity: true,
    qrCodeValue: 'QR-MID-VAULT-01',
  },
  {
    id: 'cp-mid-02',
    name: 'CP-02: Heavy HGV Freight Bay 8 Outbound Dock',
    siteId: 'site-midrand-logistics',
    location: { x: 75, y: 50 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; inspect container tamper-evident bolt seals',
    minDwellSeconds: 45,
    targetWindowMinutes: 25,
    isHighSecurity: false,
    qrCodeValue: 'QR-MID-DOCK-02',
  },

  // Century City Checkpoints
  {
    id: 'cp-cpt-01',
    name: 'CP-01: Subsea Cable Landing Manhole & Fiber Vault',
    siteId: 'site-century-city-cyber',
    location: { x: 25, y: 25 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; verify physical dual-cylinder security padlocks',
    minDwellSeconds: 60,
    targetWindowMinutes: 15,
    isHighSecurity: true,
    qrCodeValue: 'QR-CPT-SUBSEA-01',
  },
  {
    id: 'cp-cpt-02',
    name: 'CP-02: Hyperscale Server Hall A Mantrap Tag',
    siteId: 'site-century-city-cyber',
    location: { x: 70, y: 30 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; verify clean agent gas pressure cylinder gauge',
    minDwellSeconds: 45,
    targetWindowMinutes: 20,
    isHighSecurity: true,
    qrCodeValue: 'QR-CPT-HALL-02',
  },

  // Durban Port Checkpoints
  {
    id: 'cp-dbn-01',
    name: 'CP-01: Pier 2 Gantry Base & ISPS Maritime Tag',
    siteId: 'site-durban-port-terminal',
    location: { x: 30, y: 35 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; verify deepwater naval barrier & perimeter beam',
    minDwellSeconds: 45,
    targetWindowMinutes: 20,
    isHighSecurity: true,
    qrCodeValue: 'QR-DBN-PIER-01',
  },
  {
    id: 'cp-dbn-02',
    name: 'CP-02: Transnet Rail Freight Siding Lock',
    siteId: 'site-durban-port-terminal',
    location: { x: 75, y: 50 },
    type: 'QR Code Scan',
    requiredAction: 'Scan QR tag; verify rail turnout lock and CCTV blind-spot',
    minDwellSeconds: 45,
    targetWindowMinutes: 25,
    isHighSecurity: true,
    qrCodeValue: 'QR-DBN-RAIL-02',
  },
];

export const INITIAL_GUARDS: Guard[] = [
  // Sandton Officers
  {
    id: 'guard-san-01',
    name: 'Officer Sipho Khumalo',
    badgeNumber: 'PSIRA-JHB-8841',
    phone: '+27 (0) 82 555 1042',
    email: 'sipho.khumalo@aegisops.co.za',
    tier: 'Armed Security',
    status: 'patrolling',
    siteId: 'site-sandton-citadel',
    siteName: 'Sandton Financial Citadel & Corporate Vaults',
    batteryLevel: 96,
    signalStrength: 98,
    signalType: '5G',
    bodycamActive: true,
    bodycamStreamUrl: 'rtsp://soc-stream.aegis.co.za/live/san-01',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    currentTourId: 'tour-san-01',
    lastPingTime: 'Just now',
    lastScannedQRCode: 'QR-SAN-VAULT-01',
    lastScannedCheckpointId: 'cp-san-01',
    lastScannedCheckpointName: 'CP-01: Sovereign Bullion Vault Dual-Airlock Tag',
    lastScannedTimestamp: '11:28 SAST',
    heartRate: 74,
    location: { x: 25, y: 25, lat: -26.1076, lng: 28.0567, heading: 90, speedKmh: 0 },
    breadcrumbs: [
      { x: 50, y: 65, time: '11:10 SAST', qrCode: 'QR-SAN-GATE-03', checkpointName: 'CP-03: Perimeter North Gate ANPR' },
      { x: 25, y: 25, time: '11:28 SAST', qrCode: 'QR-SAN-VAULT-01', checkpointName: 'CP-01: Sovereign Bullion Vault Dual-Airlock Tag' },
    ],
  },
  {
    id: 'guard-san-02',
    name: 'Officer Zanele Ndlovu',
    badgeNumber: 'PSIRA-JHB-9012',
    phone: '+27 (0) 83 555 2088',
    email: 'zanele.ndlovu@aegisops.co.za',
    tier: 'Armed Security',
    status: 'on_duty',
    siteId: 'site-sandton-citadel',
    siteName: 'Sandton Financial Citadel & Corporate Vaults',
    batteryLevel: 88,
    signalStrength: 95,
    signalType: '5G',
    bodycamActive: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastPingTime: '1m ago',
    lastScannedQRCode: 'QR-SAN-POWER-02',
    lastScannedCheckpointId: 'cp-san-02',
    lastScannedCheckpointName: 'CP-02: Hybrid BESS Solar & Diesel Power Core',
    lastScannedTimestamp: '11:15 SAST',
    heartRate: 78,
    location: { x: 70, y: 25, lat: -26.1072, lng: 28.0571, heading: 180, speedKmh: 0 },
    breadcrumbs: [],
  },

  // Midrand Officers
  {
    id: 'guard-mid-01',
    name: 'Officer Willem de Klerk',
    badgeNumber: 'PSIRA-JHB-4410',
    phone: '+27 (0) 82 555 3391',
    email: 'willem.deklerk@aegisops.co.za',
    tier: 'Armed Security',
    status: 'patrolling',
    siteId: 'site-midrand-logistics',
    siteName: 'Midrand High-Tech Logistics & Bonded Freight Hub',
    batteryLevel: 91,
    signalStrength: 92,
    signalType: '5G',
    bodycamActive: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    lastPingTime: 'Just now',
    lastScannedQRCode: 'QR-MID-VAULT-01',
    lastScannedCheckpointId: 'cp-mid-01',
    lastScannedCheckpointName: 'CP-01: Bonded Cold-Chain Pharmaceutical Vault',
    lastScannedTimestamp: '11:22 SAST',
    heartRate: 71,
    location: { x: 30, y: 30, lat: -25.9984, lng: 28.1263, heading: 45, speedKmh: 4 },
    breadcrumbs: [],
  },

  // Century City Cape Town Officers
  {
    id: 'guard-cpt-01',
    name: 'Officer Naledi Sithole',
    badgeNumber: 'PSIRA-CPT-7721',
    phone: '+27 (0) 84 555 9011',
    email: 'naledi.sithole@aegisops.co.za',
    tier: 'Armed Security',
    status: 'patrolling',
    siteId: 'site-century-city-cyber',
    siteName: 'Century City Cyber Park & Subsea Cable Landing',
    batteryLevel: 89,
    signalStrength: 97,
    signalType: '5G',
    bodycamActive: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastPingTime: 'Just now',
    lastScannedQRCode: 'QR-CPT-SUBSEA-01',
    lastScannedCheckpointId: 'cp-cpt-01',
    lastScannedCheckpointName: 'CP-01: Subsea Cable Landing Manhole & Fiber Vault',
    lastScannedTimestamp: '11:27 SAST',
    heartRate: 68,
    location: { x: 25, y: 25, lat: -33.8927, lng: 18.5113, heading: 270, speedKmh: 0 },
    breadcrumbs: [],
  },

  // Durban Port Officers
  {
    id: 'guard-dbn-01',
    name: 'Officer Lungile Mthembu',
    badgeNumber: 'PSIRA-DBN-3319',
    phone: '+27 (0) 83 555 4910',
    email: 'lungile.mthembu@aegisops.co.za',
    tier: 'Armed Security',
    status: 'patrolling',
    siteId: 'site-durban-port-terminal',
    siteName: 'Durban Port & Bayhead Container Logistics Terminal',
    batteryLevel: 95,
    signalStrength: 94,
    signalType: '5G',
    bodycamActive: true,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    lastPingTime: 'Just now',
    lastScannedQRCode: 'QR-DBN-PIER-01',
    lastScannedCheckpointId: 'cp-dbn-01',
    lastScannedCheckpointName: 'CP-01: Pier 2 Gantry Base & ISPS Maritime Tag',
    lastScannedTimestamp: '11:29 SAST',
    heartRate: 70,
    location: { x: 30, y: 35, lat: -29.8789, lng: 31.0218, heading: 90, speedKmh: 0 },
    breadcrumbs: [],
  },
];

export const INITIAL_TOURS: PatrolTour[] = [
  {
    id: 'tour-san-01',
    name: 'Sandton Financial Citadel Hourly QR Verification Tour',
    siteId: 'site-sandton-citadel',
    siteName: 'Sandton Financial Citadel & Corporate Vaults',
    guardId: 'guard-san-01',
    guardName: 'Officer Sipho Khumalo',
    tier: 'Armed Security',
    startTime: '11:00 SAST',
    estimatedEndTime: '11:45 SAST',
    status: 'In Progress',
    complianceRate: 67,
    routeCoordinates: [
      { x: 50, y: 65 },
      { x: 25, y: 25 },
      { x: 70, y: 25 },
    ],
    checkpoints: [
      {
        checkpointId: 'cp-san-03',
        checkpointName: 'CP-03: Perimeter North Gate ANPR',
        scheduledTime: '11:10 SAST',
        completedTime: '11:10 SAST',
        status: 'Completed',
        verificationType: 'QR Code Scan',
        notes: 'Barcode tag verified; hydraulic spike barrier pressure 180 bar nominal.',
        dwellSecondsSpent: 42,
      },
      {
        checkpointId: 'cp-san-01',
        checkpointName: 'CP-01: Sovereign Bullion Vault Dual-Airlock Tag',
        scheduledTime: '11:25 SAST',
        completedTime: '11:28 SAST',
        status: 'Completed',
        verificationType: 'QR Code Scan',
        notes: 'Retina airlock seal locked. Vault magnetic locks green.',
        dwellSecondsSpent: 55,
      },
      {
        checkpointId: 'cp-san-02',
        checkpointName: 'CP-02: Hybrid BESS Solar & Diesel Power Core',
        scheduledTime: '11:40 SAST',
        status: 'Pending',
      },
    ],
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-za-01',
    incidentNumber: 'CAS-2026-JHB01',
    title: 'Sandton Citadel North Perimeter Smartcard Access Rejection',
    type: 'Unauthorized Access',
    severity: 'High',
    status: 'Investigating',
    siteId: 'site-sandton-citadel',
    siteName: 'Sandton Financial Citadel & Corporate Vaults',
    zoneName: 'Sovereign Bullion & SWIFT Vault Core',
    location: { x: 25, y: 25, lat: -26.1076, lng: 28.0567 },
    reportedByGuardId: 'guard-san-01',
    reportedByGuardName: 'Officer Sipho Khumalo (PSIRA-JHB-8841)',
    assignedResponderId: 'guard-san-01',
    assignedResponderName: 'Officer Sipho Khumalo',
    timestamp: '11:26 SAST (12m ago)',
    description:
      'Proximity biometric reader rejected unrecognized RFID badge at Subterranean Vault Mantrap. Officer Khumalo dispatched via QR-verified tour to secure and log the event.',
    policeNotified: false,
    evidence: [],
    timeline: [
      {
        id: 'tl-101',
        timestamp: '11:26 SAST',
        actor: 'Vault Access Controller #V-03',
        action: 'Card Badge Access Denied Alarm',
        details: 'Badge ID #ZA-8801 rejected: Revoked credentials.',
        type: 'creation',
      },
    ],
  },
];

export const INITIAL_SHIFTS: ShiftSchedule[] = [
  {
    id: 'shift-101',
    guardId: 'guard-san-01',
    guardName: 'Officer Sipho Khumalo',
    guardBadge: 'PSIRA-JHB-8841',
    guardTier: 'Armed Security',
    siteId: 'site-sandton-citadel',
    siteName: 'Sandton Financial Citadel & Corporate Vaults',
    dayOfWeek: 'Mon',
    date: '2026-08-17',
    startTime: '07:00',
    endTime: '15:00',
    shiftType: 'Day Shift',
    status: 'Clocked In',
    hourlyRate: 145, // Rands per hour
  },
  {
    id: 'shift-102',
    guardId: 'guard-mid-01',
    guardName: 'Officer Willem de Klerk',
    guardBadge: 'PSIRA-JHB-4410',
    guardTier: 'Armed Security',
    siteId: 'site-midrand-logistics',
    siteName: 'Midrand High-Tech Logistics & Bonded Freight Hub',
    dayOfWeek: 'Mon',
    date: '2026-08-17',
    startTime: '06:00',
    endTime: '14:00',
    shiftType: 'Day Shift',
    status: 'Clocked In',
    hourlyRate: 135,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-101',
    guardId: 'guard-san-01',
    guardName: 'Officer Sipho Khumalo',
    badgeNumber: 'PSIRA-JHB-8841',
    siteId: 'site-sandton-citadel',
    siteName: 'Sandton Financial Citadel & Corporate Vaults',
    date: '2026-08-17',
    scheduledIn: '07:00 SAST',
    actualIn: '06:54 SAST',
    scheduledOut: '15:00 SAST',
    geofenceStatus: 'Verified Inside',
    geofenceDistanceMeters: 4,
    totalHours: 8,
    overtimeHours: 0,
    selfieVerificationUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'Approved',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-2026-008',
    invoiceNumber: 'INV-ZA-2026-008',
    tenantId: 'tenant-apex',
    tenantName: 'Aegis Southern Africa & Critical Infrastructure',
    billingPeriod: '1 Aug 2026 - 31 Aug 2026',
    issueDate: '15 Aug 2026',
    dueDate: '31 Aug 2026',
    status: 'Pending',
    subtotal: 247826.09,
    tax: 37173.91, // 15% South African VAT
    total: 285000,
    items: [
      { id: 'item-1', description: '24/7 PSIRA Grade A Armed Reaction Fleet & Citadel Protection', quantity: 720, unit: 'hours', rate: 195, amount: 140400 },
      { id: 'item-2', description: 'Physical QR-Verified High-Frequency Tactical Checkpoint Tours', quantity: 450, unit: 'patrols', rate: 150, amount: 67500 },
      { id: 'item-3', description: 'SOC Enterprise CAD Link & SAPS Emergency Bridge Integration', quantity: 1, unit: 'month', rate: 77100, amount: 77100 },
    ],
  },
];

export const INITIAL_BROADCASTS: BroadcastMessage[] = [
  {
    id: 'bc-101',
    tenantId: 'tenant-apex',
    sender: 'National SOC Controller (Sandton Central)',
    senderRole: 'SOC Watch Commander',
    timestamp: '10:00 SAST',
    targetScope: 'all_sites',
    priority: 'Urgent',
    subject: 'PSIRA QR Checkpoint Protocol & Loadshedding Standby',
    message: 'All Southern Africa stations: Maintain strict physical QR scan compliance. Verify automated solar/generator hybrid cut-over readiness.',
    deliveredCount: 56,
    acknowledgedCount: 54,
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-101',
    title: 'Southern Africa Grid & Relay Synchronized',
    message: 'Gauteng, Western Cape, KZN, and SADC cross-border sites connected via encrypted fiber relays.',
    timestamp: '11:25 SAST',
    read: false,
    type: 'system',
  },
];
